fix: appease eslint
Note that build fails due to TypeScript errors:

```
$ ember build
WARNING: Node v18.2.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
Environment: development
tests/integration/components/my-component-test.ts:15:24 - error TS2531: Object is possibly 'null'.

15     assert.strictEqual(this.element.textContent.trim(), '');
                          ~~~~~~~~~~~~~~~~~~~~~~~~

tests/integration/components/my-component-test.ts:24:24 - error TS2531: Object is possibly 'null'.

24     assert.strictEqual(this.element.textContent.trim(), 'template block text');
                          ~~~~~~~~~~~~~~~~~~~~~~~~

cleaning up...
Typechecking failed

Stack Trace and Error Report: /tmp/error.dump.61db20c7195ff6cedc87f9b920f255c4.log
```